img  = imread('neggg.jpg'); 
i7 = img; 
i6 = img; 
i5 = img; 
i4 = img; 
i3 = img; 
i2 = img; 
i1 = img; 
i0 = img; 
i7 = double(bitand(img,128)); 
i6 = double(bitand(img,64)); 
i5 = double(bitand(img,32));  
i4 = double(bitand(img,16)); 
i3 = double(bitand(img,8));   
i2 = double(bitand(img,4)); 
i1 = double(bitand(img,2));   
i0 = double(bitand(img,1)); 
subplot(2,2,1); 
imshow(i7); 
title('Bit plane 7'); 
subplot(2,2,2); 
imshow(i6); 
title('Bit plane 6'); 
subplot(2,2,3); 
imshow(i5); 
title('Bit plane 5'); 
subplot(2,2,4); 
imshow(i4); 
title('Bit plane 4'); 
subplot(2,2,1); 
imshow(i3); 
title('Bit plane 3'); 
subplot(2,2,2); 
imshow(i2); 
title('Bit plane 2'); 
subplot(2,2,3); 
imshow(i1); 
title('Bit plane 1'); 
subplot(2,2,4); 
imshow(i0); 
title('Bit plane 0');
