img  = imread('neggg.jpg'); 
rmin = min(img(:)); 
rmax = max(img(:)); 
r = 0:255; 
s = zeros(size(r)); 
s(1:find(s==rmin)) = 0; 
step = length(r(find(r==rmin):find(r==rmax))); 
s(find(r==rmin):find(r==rmax)) = 0:255./step:255-255./step; 
s(find(r==rmax)+1:end) = 255; 
i2 = double(img); 
i2 = [i2 - min(i2(:))] ./ max(i2(:) - min(i2(:)));        
immean = round(mean(img(:))); 
i3 = img; 
i3(find(img>=immean)) = 255; 
i3(find(img< immean)) = 0;  
subplot(2,2,1); 
plot(r,s); 
axis([0 255 -2 259]); 
xlabel('Input Gray Level, r'); 
ylabel('Output Gray Level, s'); 
subplot(2,2,2); 
imshow(img); 
title('Original Image'); 
subplot(2,2,3); 
imshow(i2); 
title('Contrast Stretched'); 
subplot(2,2,4); 
imshow(i3); 
title('Thresholded'); 
